# Generated by Django 4.1.6 on 2023-03-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=50, verbose_name='Автор'),
        ),
    ]
